### ISSUE TITLE
CLI in Ubuntu

### ISSUE THREAD

**Issue by Mennaruuk** [shadowjohn/mypyTranscriber#1]
Hello shadowjohn, how are you.

I am currently running Ubuntu. How can I run mypyTranscriber via CLI on Ubuntu? I noticed the command has main.exe, which unfortunately does not work in Linux.

Thank you and have a great day.
Mennaruuk

**Comment by shadowjohn** [comment]
![image](https://user-images.githubusercontent.com/1788472/150150212-35e9b907-c75c-490b-bf8a-cfa374db3ab2.png)

**Comment by Mennaruuk** [comment]
shadowjohn, thank you for your help.

When I tried to transcribe to Arabic, I only got output in English and Chinese. Why is that? Also, is there a way to get an SRT and timestamps like with pyTranscriber?

Regards,
Mennaruuk

**Comment by shadowjohn** [comment]
You can use autosub or other transcribe sub tool :)
My cli version only play wav to txt (English and Chinese only)
